version: 2.1
orbs:
  node: circleci/node@4.7.0
  heroku: circleci/heroku@1.2.6

jobs:
  test:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test
          name: Run tests

workflows:
  test_and_deploy:
    jobs:
      - test:
          filters:
            branches:
              only: develop
      - heroku/deploy-via-git:
          force: true
          filters:
            branches:
               only: main 
